export enum ActionNames {
    ADD_PRODUCT = "ADD_PRODUCT",
    LOAD_PRODUCTS = "LOAD_PRODUCTS",
    REMOVE_PRODUCT = "REMOVE_PRODUCT",
    UPDATE_PRODUCT = "UPDATE_PRODUCT",
    GET_PRODUCT = "GET_PRODUCT",

    LOGIN_USER = "LOGIN_USER",
    LOGOUT_USER = "LOGOUT_USER",
    LOAD_USER = "LOAD_USER",
    SAVE_USER = "SAVE_USER",

    BEGIN_REQUEST = "BEGIN_REQUEST",
    END_REQUEST = "END_REQUEST",
}