export enum ActionNames {
    ADD_PRODUCT = "ADD_PRODUCT",
    LOAD_PRODUCTS = "LOAD_PRODUCTS",
    REMOVE_PRODUCT = "REMOVE_PRODUCT",
    UPDATE_PRODUCT = "UPDATE_PRODUCT",
    GET_PRODUCT = "GET_PRODUCT"
}